### ISSUE TITLE
periodic update checks

### ISSUE THREAD

**Issue by turboc1208** [rfverbruggen/rachiopy#12]
I really like this api wrapper you have developed.  Thank you.  I have notifications setup and am notified when a zone turns on or off manually (I haven't tested scheduled events yet).  Considering that it is possible that my computer may be turned off and re-started while a zone is running, what is the best way to get the current status of that zone (running or not)?

**Comment by rfverbruggen** [comment]
Hi @turboc1208,

Thanks for the feedback on the API wrapper and I'm happy to hear you like it.

I don't know how to get the current status of a zone. Tried to look it up on the Rachio documentation and forum, but unfortunately without success.

If we can find a solution I will definitely incorporate it in the API wrapper.

Kind regards,

Robbert

**Comment by turboc1208** [comment]
Everything that happens with rachio is done as a schedule.  Even when you manually kick off a run, it creates a schedule to track it.  So use the device.current_schedule call to check on the current status of a zone.
Chip

**Comment by rfverbruggen** [comment]
Hi Chip,

Yeah I get that. But the API Wrapper is capable of executing this call. You should:

1. r.person.getInfo(): to get your user  info (which returns an ID)
2. r.person.get(id): with the ID from step 1 (which return your devices)
3. r.device.getCurrentSchedule(id): with the ID from one of the devices from step 2 (which returns the zoneId that is currently running)

Is this enough information for you? If not, would you be able to explain your scenario with some more information?

Kind regards,

Robbert

**Comment by turboc1208** [comment]
Yes, that’s what I’m doing.

**Comment by rfverbruggen** [comment]
Hi Chip,

Ok, then I'll close the issue.

Kind regards,

Robbert
