### ISSUE TITLE
error generated in r.device.off

### ISSUE THREAD

**Issue by munnecke** [rfverbruggen/rachiopy#3]
r.device.off(id)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-f6e9c3763b51> in <module>()
----> 1 r.device.off(id)

/root/anaconda/lib/python2.7/site-packages/RachioPy-0.1-py2.7.egg/rachiopy/device.pyc in off(self, id)
     58                 body = { 'id' : id }
     59 
---> 60                 (resp, content) = self.rachio.h.request(url, 'PUT', body=body, header=self.rachio.headers)
     61                 return content

TypeError: request() got an unexpected keyword argument 'header'

**Comment by rfverbruggen** [comment]
Thank for reporting the issue.

Should be headers instead of header.

Solved it in the newest commit.
