### ISSUE TITLE
notification.add and notification.update json errors

### ISSUE THREAD

**Issue by brg468** [rfverbruggen/rachiopy#41]
Calling` notification.add` and `notification.update` methods producing errors as shown below. 

`({'date': 'Tue, 06 Oct 2020 15:41:09 GMT', 'content-type': 'application/json;charset=utf-8', 'content-length': '226', 'connection': 'keep-alive', 'server': 'nginx/1.12.1', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'x-xss-protection': '1; mode=block', 'x-frame-options': 'DENY', 'x-content-type-options': 'nosniff', 'x-ratelimit-limit': '1700', 'x-ratelimit-remaining': '1584', 'x-ratelimit-reset': '2020-10-07T00:00:00Z', 'status': 500}, {'code': '400', 'error': "Unrecognized token 'device': was expecting ('true', 'false' or 'null')\n at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@1a01b38c; line: 1, column: 8]"})`

Also see comment: https://github.com/rfverbruggen/rachiopy/pull/30#issuecomment-704447783

**Comment by rfverbruggen** [comment]
rachiopy 1.0.2 is released, the issues should now be fixed. Could you please verify and close the issue?

**Comment by brg468** [comment]
Fixed in #42. Thanks!
